/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smallworld.view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Darty
 */
public class MyWindow extends javax.swing.JFrame {
    boolean redeploy;
    int numberClickedLand;
    DefaultListModel listModel;
    ArrayList<Population> listPopulation;
    /**
     * Creates new form MyWindow
     */
    public MyWindow() {
        initComponents();
        init();
        fillDescPop();
        
    }
    
    public void fillListPopulation() // remplit la Jlist
    {
        listModel=new DefaultListModel();
        listPopulation= new ArrayList<>();
        
        for(int i=0;i<5;i++)
        {
            listPopulation.add(new Population("pop"+i, "power"+i, "desc"+i));
        }
        
        
        for(int i =0;i<listPopulation.size();i++)
        {
           listModel.addElement(listPopulation.get(i));
        }
        listPeuple.setModel(listModel);
    }
    
    public void fillDescPop() // ajoute un listener à la Jlist.
    {
        //Lorsqu'on clique sur une ligne de la JList, on remplit le textArea qui affiche la description de la population
        listPeuple.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                System.out.println(listPeuple.getSelectedIndex());
            textAreaDescription.setText(listPopulation.get(listPeuple.getSelectedIndex()).getDescription());
            }
        });
    }
    
    
    public void init()
    {
        panelGame.setVisible(false);
        buttonEndTurn.setVisible(false);
       // buttonRedeploy.setVisible(true);
        redeploy=false;
        fillListPopulation();
        
    }
    
    public void landsClick(int ncl)
    {
        numberClickedLand=ncl;
        System.out.println(ncl);
        if(redeploy== false)
        {
            /*.
             * attack
             */
            System.out.println("J'attaque la case "+ncl);
        }
        else
        {
            System.out.println("Je ne peux plus attaquer car je suis en train de redéployer");
        }
        
    }

   
;    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGame = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPeuple = new javax.swing.JList();
        buttonRedeploy = new javax.swing.JButton();
        panelTerritoires = new javax.swing.JPanel();
        land1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        land2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        land3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        land4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        land5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        land11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        land10 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        land9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        land8 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        land7 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        land16 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        land15 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        land14 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        land13 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        land12 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        land21 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        land20 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        land19 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        land18 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        land17 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        land28 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        land27 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        land26 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        land25 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        land24 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        land30 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        land0 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        land6 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        land22 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        land29 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        land23 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        buttonEndTurn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaDescription = new javax.swing.JTextArea();
        labelDesc = new javax.swing.JLabel();
        panelAccueil = new javax.swing.JPanel();
        buttonPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGame.setBackground(new java.awt.Color(255, 204, 153));

        listPeuple.setBackground(new java.awt.Color(204, 204, 204));
        listPeuple.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listPeuple);

        buttonRedeploy.setText("Redéployer");
        buttonRedeploy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRedeployMouseClicked(evt);
            }
        });

        panelTerritoires.setBackground(new java.awt.Color(204, 204, 204));
        panelTerritoires.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTerritoires.setForeground(new java.awt.Color(0, 153, 255));

        land1.setBackground(new java.awt.Color(255, 51, 51));
        land1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land1MouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("1");

        javax.swing.GroupLayout land1Layout = new javax.swing.GroupLayout(land1);
        land1.setLayout(land1Layout);
        land1Layout.setHorizontalGroup(
            land1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land1Layout.setVerticalGroup(
            land1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land2.setBackground(new java.awt.Color(204, 204, 0));
        land2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land2MouseClicked(evt);
            }
        });

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land2Layout = new javax.swing.GroupLayout(land2);
        land2.setLayout(land2Layout);
        land2Layout.setHorizontalGroup(
            land2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land2Layout.setVerticalGroup(
            land2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land3.setBackground(new java.awt.Color(255, 51, 51));
        land3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land3MouseClicked(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land3Layout = new javax.swing.GroupLayout(land3);
        land3.setLayout(land3Layout);
        land3Layout.setHorizontalGroup(
            land3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land3Layout.setVerticalGroup(
            land3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land3Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land4.setBackground(new java.awt.Color(204, 0, 204));
        land4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land4MouseClicked(evt);
            }
        });

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land4Layout = new javax.swing.GroupLayout(land4);
        land4.setLayout(land4Layout);
        land4Layout.setHorizontalGroup(
            land4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land4Layout.setVerticalGroup(
            land4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land4Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land5.setBackground(new java.awt.Color(0, 153, 153));
        land5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land5MouseClicked(evt);
            }
        });

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("1");

        javax.swing.GroupLayout land5Layout = new javax.swing.GroupLayout(land5);
        land5.setLayout(land5Layout);
        land5Layout.setHorizontalGroup(
            land5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land5Layout.setVerticalGroup(
            land5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land5Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land11.setBackground(new java.awt.Color(255, 51, 51));
        land11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land11MouseClicked(evt);
            }
        });

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land11Layout = new javax.swing.GroupLayout(land11);
        land11.setLayout(land11Layout);
        land11Layout.setHorizontalGroup(
            land11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land11Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land11Layout.setVerticalGroup(
            land11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land11Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land10.setBackground(new java.awt.Color(204, 204, 0));
        land10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land10MouseClicked(evt);
            }
        });

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land10Layout = new javax.swing.GroupLayout(land10);
        land10.setLayout(land10Layout);
        land10Layout.setHorizontalGroup(
            land10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land10Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land10Layout.setVerticalGroup(
            land10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land10Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land9.setBackground(new java.awt.Color(0, 153, 153));
        land9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land9MouseClicked(evt);
            }
        });

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land9Layout = new javax.swing.GroupLayout(land9);
        land9.setLayout(land9Layout);
        land9Layout.setHorizontalGroup(
            land9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land9Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land9Layout.setVerticalGroup(
            land9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land9Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land8.setBackground(new java.awt.Color(0, 153, 153));
        land8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land8MouseClicked(evt);
            }
        });

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land8Layout = new javax.swing.GroupLayout(land8);
        land8.setLayout(land8Layout);
        land8Layout.setHorizontalGroup(
            land8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land8Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land8Layout.setVerticalGroup(
            land8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land8Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land7.setBackground(new java.awt.Color(255, 51, 51));
        land7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land7MouseClicked(evt);
            }
        });

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land7Layout = new javax.swing.GroupLayout(land7);
        land7.setLayout(land7Layout);
        land7Layout.setHorizontalGroup(
            land7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land7Layout.setVerticalGroup(
            land7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land7Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land16.setBackground(new java.awt.Color(102, 102, 102));
        land16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land16MouseClicked(evt);
            }
        });

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land16Layout = new javax.swing.GroupLayout(land16);
        land16.setLayout(land16Layout);
        land16Layout.setHorizontalGroup(
            land16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land16Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land16Layout.setVerticalGroup(
            land16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land16Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land15.setBackground(new java.awt.Color(102, 102, 102));
        land15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land15MouseClicked(evt);
            }
        });

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("1");

        javax.swing.GroupLayout land15Layout = new javax.swing.GroupLayout(land15);
        land15.setLayout(land15Layout);
        land15Layout.setHorizontalGroup(
            land15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land15Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land15Layout.setVerticalGroup(
            land15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land15Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land14.setBackground(new java.awt.Color(204, 0, 204));
        land14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land14MouseClicked(evt);
            }
        });

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("1");

        javax.swing.GroupLayout land14Layout = new javax.swing.GroupLayout(land14);
        land14.setLayout(land14Layout);
        land14Layout.setHorizontalGroup(
            land14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land14Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land14Layout.setVerticalGroup(
            land14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land14Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land13.setBackground(new java.awt.Color(204, 204, 0));
        land13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land13MouseClicked(evt);
            }
        });

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land13Layout = new javax.swing.GroupLayout(land13);
        land13.setLayout(land13Layout);
        land13Layout.setHorizontalGroup(
            land13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land13Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land13Layout.setVerticalGroup(
            land13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land13Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land12.setBackground(new java.awt.Color(204, 204, 0));
        land12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land12MouseClicked(evt);
            }
        });

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land12Layout = new javax.swing.GroupLayout(land12);
        land12.setLayout(land12Layout);
        land12Layout.setHorizontalGroup(
            land12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land12Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land12Layout.setVerticalGroup(
            land12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land12Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land21.setBackground(new java.awt.Color(0, 153, 153));
        land21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land21MouseClicked(evt);
            }
        });

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land21Layout = new javax.swing.GroupLayout(land21);
        land21.setLayout(land21Layout);
        land21Layout.setHorizontalGroup(
            land21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land21Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land21Layout.setVerticalGroup(
            land21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land21Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land20.setBackground(new java.awt.Color(204, 204, 0));
        land20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land20MouseClicked(evt);
            }
        });

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land20Layout = new javax.swing.GroupLayout(land20);
        land20.setLayout(land20Layout);
        land20Layout.setHorizontalGroup(
            land20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land20Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land20Layout.setVerticalGroup(
            land20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land20Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land19.setBackground(new java.awt.Color(255, 51, 51));
        land19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land19MouseClicked(evt);
            }
        });

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land19Layout = new javax.swing.GroupLayout(land19);
        land19.setLayout(land19Layout);
        land19Layout.setHorizontalGroup(
            land19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land19Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land19Layout.setVerticalGroup(
            land19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land19Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land18.setBackground(new java.awt.Color(204, 0, 204));
        land18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land18MouseClicked(evt);
            }
        });

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land18Layout = new javax.swing.GroupLayout(land18);
        land18.setLayout(land18Layout);
        land18Layout.setHorizontalGroup(
            land18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land18Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land18Layout.setVerticalGroup(
            land18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land18Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land17.setBackground(new java.awt.Color(0, 153, 153));
        land17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land17MouseClicked(evt);
            }
        });

        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("1");

        javax.swing.GroupLayout land17Layout = new javax.swing.GroupLayout(land17);
        land17.setLayout(land17Layout);
        land17Layout.setHorizontalGroup(
            land17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land17Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land17Layout.setVerticalGroup(
            land17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land17Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land28.setBackground(new java.awt.Color(255, 51, 51));
        land28.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land28MouseClicked(evt);
            }
        });

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land28Layout = new javax.swing.GroupLayout(land28);
        land28.setLayout(land28Layout);
        land28Layout.setHorizontalGroup(
            land28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land28Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land28Layout.setVerticalGroup(
            land28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land28Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land27.setBackground(new java.awt.Color(204, 204, 0));
        land27.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land27MouseClicked(evt);
            }
        });

        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("1");

        javax.swing.GroupLayout land27Layout = new javax.swing.GroupLayout(land27);
        land27.setLayout(land27Layout);
        land27Layout.setHorizontalGroup(
            land27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land27Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land27Layout.setVerticalGroup(
            land27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land27Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land26.setBackground(new java.awt.Color(0, 153, 153));
        land26.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land26MouseClicked(evt);
            }
        });

        jLabel43.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land26Layout = new javax.swing.GroupLayout(land26);
        land26.setLayout(land26Layout);
        land26Layout.setHorizontalGroup(
            land26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land26Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land26Layout.setVerticalGroup(
            land26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land26Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land25.setBackground(new java.awt.Color(255, 51, 51));
        land25.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land25MouseClicked(evt);
            }
        });

        jLabel44.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land25Layout = new javax.swing.GroupLayout(land25);
        land25.setLayout(land25Layout);
        land25Layout.setHorizontalGroup(
            land25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land25Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land25Layout.setVerticalGroup(
            land25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land25Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land24.setBackground(new java.awt.Color(102, 102, 102));
        land24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land24MouseClicked(evt);
            }
        });

        jLabel45.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land24Layout = new javax.swing.GroupLayout(land24);
        land24.setLayout(land24Layout);
        land24Layout.setHorizontalGroup(
            land24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land24Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land24Layout.setVerticalGroup(
            land24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land24Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land30.setBackground(new java.awt.Color(0, 153, 153));
        land30.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land30MouseClicked(evt);
            }
        });

        jLabel46.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land30Layout = new javax.swing.GroupLayout(land30);
        land30.setLayout(land30Layout);
        land30Layout.setHorizontalGroup(
            land30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land30Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land30Layout.setVerticalGroup(
            land30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land30Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land0.setBackground(new java.awt.Color(0, 153, 153));
        land0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land0MouseClicked(evt);
            }
        });

        jLabel47.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land0Layout = new javax.swing.GroupLayout(land0);
        land0.setLayout(land0Layout);
        land0Layout.setHorizontalGroup(
            land0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land0Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land0Layout.setVerticalGroup(
            land0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land0Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land6.setBackground(new java.awt.Color(102, 102, 102));
        land6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land6MouseClicked(evt);
            }
        });

        jLabel48.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land6Layout = new javax.swing.GroupLayout(land6);
        land6.setLayout(land6Layout);
        land6Layout.setHorizontalGroup(
            land6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land6Layout.setVerticalGroup(
            land6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land6Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land22.setBackground(new java.awt.Color(204, 0, 204));
        land22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land22MouseClicked(evt);
            }
        });

        jLabel49.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land22Layout = new javax.swing.GroupLayout(land22);
        land22.setLayout(land22Layout);
        land22Layout.setHorizontalGroup(
            land22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land22Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land22Layout.setVerticalGroup(
            land22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land22Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land29.setBackground(new java.awt.Color(204, 0, 204));
        land29.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land29MouseClicked(evt);
            }
        });

        jLabel50.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land29Layout = new javax.swing.GroupLayout(land29);
        land29.setLayout(land29Layout);
        land29Layout.setHorizontalGroup(
            land29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land29Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land29Layout.setVerticalGroup(
            land29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land29Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        land23.setBackground(new java.awt.Color(255, 51, 51));
        land23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        land23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                land23MouseClicked(evt);
            }
        });

        jLabel51.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout land23Layout = new javax.swing.GroupLayout(land23);
        land23.setLayout(land23Layout);
        land23Layout.setHorizontalGroup(
            land23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(land23Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        land23Layout.setVerticalGroup(
            land23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, land23Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout panelTerritoiresLayout = new javax.swing.GroupLayout(panelTerritoires);
        panelTerritoires.setLayout(panelTerritoiresLayout);
        panelTerritoiresLayout.setHorizontalGroup(
            panelTerritoiresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTerritoiresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTerritoiresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(land0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTerritoiresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTerritoiresLayout.createSequentialGroup()
                        .addComponent(land1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTerritoiresLayout.createSequentialGroup()
                        .addComponent(land7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTerritoiresLayout.createSequentialGroup()
                        .addComponent(land12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTerritoiresLayout.createSequentialGroup()
                        .addComponent(land17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(land22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTerritoiresLayout.createSequentialGroup()
                        .addGroup(panelTerritoiresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTerritoiresLayout.createSequentialGroup()
                                .addComponent(land24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(land25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(land26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(land29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTerritoiresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(land30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelTerritoiresLayout.createSequentialGroup()
                                .addComponent(land27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(land28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelTerritoiresLayout.setVerticalGroup(
            panelTerritoiresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTerritoiresLayout.createSequentialGroup()
                .addGroup(panelTerritoiresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(land5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTerritoiresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(land11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTerritoiresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(land16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTerritoiresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(land21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTerritoiresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(land28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTerritoiresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(land30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(land29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        buttonEndTurn.setText("Terminer le tour");
        buttonEndTurn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEndTurnMouseClicked(evt);
            }
        });

        textAreaDescription.setColumns(20);
        textAreaDescription.setRows(5);
        jScrollPane2.setViewportView(textAreaDescription);

        labelDesc.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelDesc.setLabelFor(textAreaDescription);
        labelDesc.setText("Description:");

        javax.swing.GroupLayout panelGameLayout = new javax.swing.GroupLayout(panelGame);
        panelGame.setLayout(panelGameLayout);
        panelGameLayout.setHorizontalGroup(
            panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGameLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTerritoires, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buttonEndTurn)
                        .addComponent(buttonRedeploy)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                        .addComponent(jScrollPane2))
                    .addComponent(labelDesc))
                .addContainerGap())
        );
        panelGameLayout.setVerticalGroup(
            panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGameLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTerritoires, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelGameLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(labelDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRedeploy)
                    .addComponent(buttonEndTurn))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        panelAccueil.setBackground(new java.awt.Color(204, 204, 204));
        panelAccueil.setAutoscrolls(true);

        buttonPlay.setText("Jouer");
        buttonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAccueilLayout = new javax.swing.GroupLayout(panelAccueil);
        panelAccueil.setLayout(panelAccueilLayout);
        panelAccueilLayout.setHorizontalGroup(
            panelAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        panelAccueilLayout.setVerticalGroup(
            panelAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelAccueilLayout.createSequentialGroup()
                .addGap(611, 611, 611)
                .addComponent(buttonPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addComponent(panelAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 8, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelAccueil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayActionPerformed
        // TODO add your handling code here:
        panelAccueil.setVisible(false);
        panelGame.setVisible(true);
    }//GEN-LAST:event_buttonPlayActionPerformed

    private void land0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land0MouseClicked
        // TODO add your handling code here:
        landsClick(0);
        
    }//GEN-LAST:event_land0MouseClicked

    private void land1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land1MouseClicked
        // TODO add your handling code here:
        landsClick(1);
    }//GEN-LAST:event_land1MouseClicked

    private void land2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land2MouseClicked
        // TODO add your handling code here:
        landsClick(2);
    }//GEN-LAST:event_land2MouseClicked

    private void land3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land3MouseClicked
        // TODO add your handling code here:
        landsClick(3);
    }//GEN-LAST:event_land3MouseClicked

    private void land4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land4MouseClicked
        // TODO add your handling code here:
        landsClick(4);
    }//GEN-LAST:event_land4MouseClicked

    private void land5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land5MouseClicked
        // TODO add your handling code here:
        landsClick(5);
    }//GEN-LAST:event_land5MouseClicked

    private void land6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land6MouseClicked
        // TODO add your handling code here:
        landsClick(6);
    }//GEN-LAST:event_land6MouseClicked

    private void land7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land7MouseClicked
        // TODO add your handling code here:
        landsClick(7);
    }//GEN-LAST:event_land7MouseClicked

    private void land8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land8MouseClicked
        // TODO add your handling code here:
        landsClick(8);
    }//GEN-LAST:event_land8MouseClicked

    private void land9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land9MouseClicked
        // TODO add your handling code here:
        landsClick(9);
    }//GEN-LAST:event_land9MouseClicked

    private void land10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land10MouseClicked
        // TODO add your handling code here:
        landsClick(10);
    }//GEN-LAST:event_land10MouseClicked

    private void land11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land11MouseClicked
        // TODO add your handling code here:
        landsClick(11);
    }//GEN-LAST:event_land11MouseClicked

    private void land12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land12MouseClicked
        // TODO add your handling code here:
        landsClick(12);
    }//GEN-LAST:event_land12MouseClicked

    private void land13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land13MouseClicked
        // TODO add your handling code here:
        landsClick(13);
    }//GEN-LAST:event_land13MouseClicked

    private void land14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land14MouseClicked
        // TODO add your handling code here:
        landsClick(14);
    }//GEN-LAST:event_land14MouseClicked

    private void land15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land15MouseClicked
        // TODO add your handling code here:
        landsClick(15);
    }//GEN-LAST:event_land15MouseClicked

    private void land16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land16MouseClicked
        // TODO add your handling code here:
        landsClick(16);
    }//GEN-LAST:event_land16MouseClicked

    private void land17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land17MouseClicked
        // TODO add your handling code here:
        landsClick(17);
    }//GEN-LAST:event_land17MouseClicked

    private void land18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land18MouseClicked
        // TODO add your handling code here:
        landsClick(18);
    }//GEN-LAST:event_land18MouseClicked

    private void land19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land19MouseClicked
        // TODO add your handling code here:
        landsClick(19);
    }//GEN-LAST:event_land19MouseClicked

    private void land20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land20MouseClicked
        // TODO add your handling code here:
        landsClick(20);
    }//GEN-LAST:event_land20MouseClicked

    private void land21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land21MouseClicked
        // TODO add your handling code here:
        landsClick(21);
    }//GEN-LAST:event_land21MouseClicked

    private void land22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land22MouseClicked
        // TODO add your handling code here:
        landsClick(22);
    }//GEN-LAST:event_land22MouseClicked

    private void land23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land23MouseClicked
        // TODO add your handling code here:
        landsClick(23);
    }//GEN-LAST:event_land23MouseClicked

    private void land24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land24MouseClicked
        // TODO add your handling code here:
        landsClick(24);
    }//GEN-LAST:event_land24MouseClicked

    private void land25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land25MouseClicked
        // TODO add your handling code here:
        landsClick(25);
    }//GEN-LAST:event_land25MouseClicked

    private void land26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land26MouseClicked
        // TODO add your handling code here:
        landsClick(26);
    }//GEN-LAST:event_land26MouseClicked

    private void land27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land27MouseClicked
        // TODO add your handling code here:
        landsClick(27);
    }//GEN-LAST:event_land27MouseClicked

    private void land28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land28MouseClicked
        // TODO add your handling code here:
        landsClick(28);
    }//GEN-LAST:event_land28MouseClicked

    private void land29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land29MouseClicked
        // TODO add your handling code here:
        landsClick(29);
    }//GEN-LAST:event_land29MouseClicked

    private void land30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_land30MouseClicked
        // TODO add your handling code here:
        landsClick(30);
    }//GEN-LAST:event_land30MouseClicked

    private void buttonRedeployMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRedeployMouseClicked
        // TODO add your handling code here:
        redeploy=true;
        buttonRedeploy.setVisible(false);
        buttonEndTurn.setVisible(true);
        JOptionPane.showMessageDialog(this,"Veuillez redéployer vos troupes"," Redéploiement ",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonRedeployMouseClicked

    private void buttonEndTurnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEndTurnMouseClicked
        // TODO add your handling code here:
        redeploy=false;
        buttonEndTurn.setVisible(false);
        buttonRedeploy.setVisible(true);
        JOptionPane.showMessageDialog(this,"Le tour est terminé"," Fin du tour ",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonEndTurnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEndTurn;
    private javax.swing.JButton buttonPlay;
    private javax.swing.JButton buttonRedeploy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDesc;
    private javax.swing.JPanel land0;
    private javax.swing.JPanel land1;
    private javax.swing.JPanel land10;
    private javax.swing.JPanel land11;
    private javax.swing.JPanel land12;
    private javax.swing.JPanel land13;
    private javax.swing.JPanel land14;
    private javax.swing.JPanel land15;
    private javax.swing.JPanel land16;
    private javax.swing.JPanel land17;
    private javax.swing.JPanel land18;
    private javax.swing.JPanel land19;
    private javax.swing.JPanel land2;
    private javax.swing.JPanel land20;
    private javax.swing.JPanel land21;
    private javax.swing.JPanel land22;
    private javax.swing.JPanel land23;
    private javax.swing.JPanel land24;
    private javax.swing.JPanel land25;
    private javax.swing.JPanel land26;
    private javax.swing.JPanel land27;
    private javax.swing.JPanel land28;
    private javax.swing.JPanel land29;
    private javax.swing.JPanel land3;
    private javax.swing.JPanel land30;
    private javax.swing.JPanel land4;
    private javax.swing.JPanel land5;
    private javax.swing.JPanel land6;
    private javax.swing.JPanel land7;
    private javax.swing.JPanel land8;
    private javax.swing.JPanel land9;
    private javax.swing.JList listPeuple;
    private javax.swing.JPanel panelAccueil;
    private javax.swing.JPanel panelGame;
    private javax.swing.JPanel panelTerritoires;
    private javax.swing.JTextArea textAreaDescription;
    // End of variables declaration//GEN-END:variables
}
